"""Initial

Revision ID: 2af87294dd98
Revises: 
Create Date: 2025-03-02 19:47:46.574474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af87294dd98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='satelite'
    )
    op.create_index(op.f('ix_satelite_users_id'), 'users', ['id'], unique=False, schema='satelite')
    op.create_index(op.f('ix_satelite_users_username'), 'users', ['username'], unique=True, schema='satelite')
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['satelite.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='satelite'
    )
    op.create_index(op.f('ix_satelite_auth_tokens_id'), 'auth_tokens', ['id'], unique=False, schema='satelite')
    op.create_index(op.f('ix_satelite_auth_tokens_token'), 'auth_tokens', ['token'], unique=False, schema='satelite')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_satelite_auth_tokens_token'), table_name='auth_tokens', schema='satelite')
    op.drop_index(op.f('ix_satelite_auth_tokens_id'), table_name='auth_tokens', schema='satelite')
    op.drop_table('auth_tokens', schema='satelite')
    op.drop_index(op.f('ix_satelite_users_username'), table_name='users', schema='satelite')
    op.drop_index(op.f('ix_satelite_users_id'), table_name='users', schema='satelite')
    op.drop_table('users', schema='satelite')
    # ### end Alembic commands ###
