"""Add satellite tracking

Revision ID: a375930e1697
Revises: 2af87294dd98
Create Date: 2025-03-02 20:13:21.393612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a375930e1697'
down_revision: Union[str, None] = '2af87294dd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('norad_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tle_line1', sa.String(), nullable=True),
    sa.Column('tle_line2', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('norad_id'),
    schema='satelite'
    )
    op.create_table('user_satellite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('norad_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['norad_id'], ['satelite.satellites.norad_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['satelite.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'norad_id'),
    schema='satelite'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_satellite', schema='satelite')
    op.drop_table('satellites', schema='satelite')
    # ### end Alembic commands ###
